# url:
# baseurl: /

# Site settings
title: Vitality Family Chiropractic
logo: /img/logo.png
email: info@vitalityfamilychiropractic.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Christie McLarty, DC, CACCP
  pic: 1
  position: Chiropractor
  social:
    - title: facebook
      url: https://www.facebook.com/drchristiemclarty/
#    - title: twitter
#      url: #
#    - title: linkedin
#      url: #
#- name: Darren Ipsum
#  pic: 2
#  position: Dweeb
#- name: Carolorem Plurebum
#  pic: 3
#  position: Stylewriter

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/vitalityfamilychiropractic/
#  - title: twitter
#    url: http://twitter.com/jekyllrb

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
